SCRIPTS=	opnsense.sh opnsense-import.sh opnsense-install.sh \
		opnsense-reset.sh opnsense-rootpass.sh opnsense-ufs.sh \
		opnsense-zfs.sh

MAN=		# not needed

PREFIX?=${DESTDIR}/usr

BINDIR=	${PREFIX}/libexec/bsdinstall

.include <bsd.prog.mk>
